version: 3
jobs:
  build:
    # Use a Linux VM insted of docker environtment
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build and spin up
          command: docker-compose up -d --build